version: "3.8"

services:
  manager:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DATABASE=manager_db
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - ADMIN_DEFAULT_PASSWORD=${ADMIN_DEFAULT_PASSWORD}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro # Mount the certs directory
    depends_on:
      - manager

volumes:
  mongo_
