version: "3.8"

services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beehive-manager
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=manager_db
      # These will be set by the setup script in the container
      - MONGODB_USER=${MONGODB_USER:-manager}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-}
      - JWT_SECRET=${JWT_SECRET:-}
      - API_KEY=${API_KEY:-}
      - API_SECRET=${API_SECRET:-}
      - ADMIN_DEFAULT_PASSWORD=${ADMIN_DEFAULT_PASSWORD:-}
      - TZ=UTC
    volumes:
      - ./certs:/app/certs:ro
      - ./logs:/app/logs
      - ./data:/app/data
      - ./.env:/app/.env
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - beehive-network

  mongo:
    image: mongo:latest
    container_name: beehive-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=manager_db
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-}
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - beehive-network

  nginx:
    image: nginx:alpine
    container_name: beehive-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - manager
    restart: unless-stopped
    networks:
      - beehive-network

volumes:
  mongo-data:
    name: beehive-mongo-data

networks:
  beehive-network:
    name: beehive-network
    driver: bridge