services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    volumes:
      - ./init-mongo-dev.js:/docker-entrypoint-initdb.d/init-mongo-dev.js:ro
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "admin", "--eval", "db.auth('admin', 'admin_password'); db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  manager:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./certs:/app/certs
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - MONGODB_URI=mongodb://manager:manager_password@mongo:27017/manager_db
      - MONGODB_DATABASE=manager_db
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - LOG_LEVEL=debug
    depends_on:
      mongo:
        condition: service_healthy
volumes:
  mongodb_data: