server:
  host: "0.0.0.0"
  port: 8080
  static_dir: "./frontend/build"  # Directory for serving the React app
  tls:
    enabled: true
    cert_file: "certs/server.crt"   # Path to your TLS certificate
    key_file: "certs/server.key"    # Path to your TLS key

mongodb:
  # TODO: Add mongo root username
  # TODO: Add mongo root password
  uri: "${MONGODB_URI}"
  database: "manager_db"

auth:
  # Sensitive values are expected to come from environment variables.
  jwt_secret: "${JWT_SECRET}"
  token_expiration_hours: 24
  api_key: "${API_KEY}"
  api_secret: "${API_SECRET}"

admin:
  default_username: "admin"
  # For security, store the hashed password in your .env file.
  default_password: "${ADMIN_DEFAULT_PASSWORD}"

logging:
  level: "info"

rate_limiter:
  max_attempts: 5
  window_seconds: 60
  blockout_minutes: 30
