server:
  host: "0.0.0.0"
  port: 8080
  static_dir: "./frontend/build"  # Directory for serving the React app
  tls:
    enabled: true
    cert_file: "certs/server.crt"   # Path to your TLS certificate
    key_file: "certs/server.key"    # Path to your TLS key

mongodb:
  uri: "mongodb://localhost:27017"
  database: "manager_db"

auth:
  # Sensitive values are now expected to come from environment variables.
  jwt_secret: "${JWT_SECRET}"          # e.g., your_super_secret_jwt_key
  token_expiration_hours: 24
  api_key: "${API_KEY}"                # e.g., expected_api_key
  api_secret: "${API_SECRET}"          # e.g., expected_api_secret

admin:
  default_username: "admin"
  # For security, store the hashed password in your .env file.
  default_password: "${ADMIN_DEFAULT_PASSWORD}"  

logging:
  level: "info"  # Can be "debug", "info", "warn", "error", etc.
