openapi: 3.0.3
info:
  title: Beehive Manager API
  description: API for managing agents and tasks in the Beehive system
  version: 1.0.0

servers:
  - url: https://{server}:8080
    variables:
      server:
        default: localhost
        description: Server hostname

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    SignatureAuth:
      type: apiKey
      in: header
      name: X-Signature

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        details:
          type: string

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        token:
          type: string
        username:
          type: string

    Agent:
      type: object
      required:
        - uuid
        - hostname
        - mac_hash
      properties:
        uuid:
          type: string
        hostname:
          type: string
        mac_hash:
          type: string
        nickname:
          type: string
        role:
          type: string
        status:
          type: string
        last_seen:
          type: string
          format: date-time

    AgentSummary:
      type: object
      properties:
        uuid:
          type: string
        nickname:
          type: string
        hostname:
          type: string
        last_seen:
          type: string
          format: date-time
        role:
          type: string

    AgentRegistrationResponse:
      type: object
      properties:
        api_key:
          type: string
        status:
          type: string
          enum: [registered]
        timestamp:
          type: string
          format: date-time

    HeartbeatRequest:
      type: object
      required:
        - uuid
        - timestamp
      properties:
        uuid:
          type: string
        timestamp:
          type: string
          format: date-time

    HeartbeatResponse:
      type: object
      properties:
        status:
          type: string
          enum: [heartbeat_received]
        timestamp:
          type: string
          format: date-time

    TaskOutput:
      type: object
      properties:
        logs:
          type: string
        error:
          type: string

    Task:
      type: object
      required:
        - agent_id
        - type
        - parameters
      properties:
        id:
          type: string
        agent_id:
          type: string
        type:
          type: string
          enum: [command_shell, file_operation, ui_automation, browser_automation]
        parameters:
          type: object
        status:
          type: string
          enum: [queued, running, completed, failed, cancelled, timeout]
        output:
          $ref: '#/components/schemas/TaskOutput'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        timeout:
          type: integer
        started_at:
          type: string
          format: date-time

    TaskCreationResponse:
      type: object
      properties:
        task_id:
          type: string
        status:
          type: string
          enum: [queued]
        timestamp:
          type: string
          format: date-time

    TaskCancelResponse:
      type: object
      properties:
        task_id:
          type: string
        status:
          type: string
          enum: [cancelled]
        timestamp:
          type: string
          format: date-time

    LogEntry:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        endpoint:
          type: string
        agent_id:
          type: string
        status:
          type: string
        details:
          type: string

    LogsResponse:
      type: object
      properties:
        logs:
          type: array
          items:
            $ref: '#/components/schemas/LogEntry'

    Role:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        applications:
          type: array
          items:
            type: string
        default_tasks:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time

paths:
  /admin/login:
    post:
      summary: Admin login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/agent/register:
    post:
      summary: Register a new agent
      security:
        - ApiKeyAuth: []
        - SignatureAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Agent'
      responses:
        '200':
          description: Agent registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentRegistrationResponse'
        '401':
          description: Authentication failed

  /api/agent/heartbeat:
    post:
      summary: Agent heartbeat
      security:
        - ApiKeyAuth: []
        - SignatureAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HeartbeatRequest'
      responses:
        '200':
          description: Heartbeat received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeartbeatResponse'
        '401':
          description: Authentication failed

  /api/agent/{agent_id}/tasks:
    get:
      summary: List Tasks for an Agent
      security:
        - ApiKeyAuth: []
        - SignatureAuth: []
      parameters:
        - in: path
          name: agent_id
          schema:
            type: string
          required: true
          description: Agent ID
      responses:
        '200':
          description: Array of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /api/task/create:
    post:
      summary: Create a new task
      security:
        - ApiKeyAuth: []
        - SignatureAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - task
              properties:
                task:
                  $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskCreationResponse'
        '400':
          description: Invalid request
        '401':
          description: Authentication failed

  /api/task/status/{task_id}:
    get:
      summary: Get task status
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      security:
        - ApiKeyAuth: []
        - SignatureAuth: []
      responses:
        '200':
          description: Task status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found

  /api/task/cancel/{task_id}:
    post:
      summary: Cancel a task
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      security:
        - ApiKeyAuth: []
        - SignatureAuth: []
      responses:
        '200':
          description: Task cancelled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskCancelResponse'
        '404':
          description: Task not found

  /admin/roles:
    get:
      summary: List All Roles
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Array of roles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
    post:
      summary: Create a New Role
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'
      responses:
        '201':
          description: Role created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'

  /admin/roles/{role_id}:
    get:
      summary: Retrieve Role Details
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: role_id
          schema:
            type: string
          required: true
          description: Role ID
      responses:
        '200':
          description: Role details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'